; M5Stack StopWatch (ESP32-S3R8, 16MB Flash, 8MB OPI PSRAM)
; USB-OTG (TinyUSB) 模式：USBHIDKeyboard + CDC 串口
[platformio]
src_dir = .

[env:stopwatch]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.311/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino
src_dir = .

monitor_speed = 115200
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv
upload_port = /dev/cu.usbmodem21101
build_flags =
    -DARDUINO_USB_MODE=0
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DBOARD_HAS_PSRAM
